### ISSUE TITLE
Calculation LP Export Inc,LP6_EXP

### ISSUE THREAD

**Issue by jgracio** [nikito7/easyhan#1]
Can you please check this parameter, as it is much lower than the value extracted from e-redes?
Thanks

**Comment by nikito7** [comment]
No e-redes dividir por 4.

Easy HAN: kWh
E-Redes: kW

**Comment by jgracio** [comment]
Obrigado pela rapiddíssima resposta
O cálculo da energia exportanda em cada período de 15 minutos parece ter uma manipulação que leva a ser atenuada e a perder precisão. Recorrendo apenas ao meu EasyHan no Tasmota posso ver o dia de hoje:

No diagrama de Energia Hoje destaca-se que exportei energia cerca das 13:00 que àquela hora é bem maior que as energia importada ou exportada a qualquer hora. 
 
![image](https://github.com/nikito7/easyhan/assets/25244815/b994cc42-a089-4e78-8267-86c6b08fc3fe)

Depois, no diagrama energia 30 dias referente a este mês, copiei apenas o dia de hoje (bem sei que as escalas dos gráficos são diferentes) 

![image](https://github.com/nikito7/easyhan/assets/25244815/209c8b1e-a7bd-4e9c-9c6d-028c4c701af6)

Mas nota-se que a energia exportada às 13:00 não é relevante relativamente a nenhuma das restantes horas do dia já que sofre uma atenuação. O mesmo se passou no dia de ontem.

Esta atenuação e perda de precisão é o valor que recebo no HA via MQTT e a que aparece no ficheiro CSV.

Obrigado pela paciência

**Comment by nikito7** [comment]
Havia um bug quando passei de Wh a kWh.

Isso também não é perfeito. (Se houver reboots)

O diagrama de carga tem 15min de atraso.

**Comment by nikito7** [comment]
Os LP-xxxx.csv deveriam estar correctos 

https://forum.cpha.pt/t/netmetering-diagrama-de-carga-load-profile-15min-settlement-2023/10893/8?u=nikito7

**Comment by jgracio** [comment]
Obrigado
O que tenho que fazer para corrigir o bug na minha configuração?

**Comment by nikito7** [comment]
Acho que ainda não percebi o problema.

LP*csv
Valores absolutos e reais.
Pode falhar linhas.
De resto é o diagrama de carga real.
No .xslx da e-redes é preciso dividir por 4 cada linha.

```js
2023-08-03T07:15,0.134,0.002
2023-08-03T07:30,0.012,0.021
2023-08-03T07:45,0.003,0.043
2023-08-03T08:00,0.019,0.058
2023-08-03T08:15,0.004,0.119
2023-08-03T08:30,0.017,0.132
2023-08-03T08:45,0.005,0.183
2023-08-03T09:00,0.010,0.215
2023-08-03T09:15,0.005,0.251
2023-08-03T09:30,0.010,0.286
2023-08-03T09:45,0.001,0.362
2023-08-03T10:00,0.034,0.344
2023-08-03T10:15,0.001,0.416
2023-08-03T10:30,0.695,0.072
2023-08-03T10:45,0.698,0.067
2023-08-03T11:00,0.760,0.000
2023-08-03T11:15,0.735,0.000
2023-08-03T11:30,0.718,0.000
2023-08-03T11:45,0.037,0.522
2023-08-03T12:00,0.000,0.578
2023-08-03T12:15,0.000,0.597
2023-08-03T12:30,0.071,0.524
2023-08-03T12:45,0.000,0.561
2023-08-03T13:00,0.001,0.581
2023-08-03T13:15,0.014,0.556
2023-08-03T13:30,0.006,0.581
2023-08-03T13:45,0.002,0.587
2023-08-03T14:00,0.002,0.604
2023-08-03T14:15,0.000,0.602
2023-08-03T14:30,0.000,0.601
2023-08-03T14:45,0.001,0.578
2023-08-03T15:00,0.001,0.544
2023-08-03T15:15,0.000,0.529
2023-08-03T15:30,0.008,0.492
2023-08-03T15:45,0.001,0.490
2023-08-03T16:00,0.639,0.106
2023-08-03T16:15,0.820,0.000
2023-08-03T16:30,0.799,0.000
2023-08-03T16:45,0.807,0.000
2023-08-03T17:00,0.841,0.000
2023-08-03T17:15,0.875,0.006
2023-08-03T17:30,0.000,0.288
2023-08-03T17:45,0.000,0.259
2023-08-03T18:00,0.001,0.227
2023-08-03T18:15,0.035,0.155
2023-08-03T18:30,0.002,0.113
2023-08-03T18:45,0.035,0.082
2023-08-03T19:00,0.038,0.042
2023-08-03T19:15,0.011,0.021
2023-08-03T19:30,0.046,0.008
2023-08-03T19:45,0.064,0.003
2023-08-03T20:00,0.041,0.001
2023-08-03T20:15,0.074,0.000
2023-08-03T20:30,0.171,0.000
2023-08-03T20:45,0.038,0.000
```

0d.csv
Precisão só de duas décimas.
Mas não influencia nada (de relevante)  no HA.
Se fizer reboot acumula na hora a seguir.
```js
2023-08-03,Import,Export
00h,0.13,0.00
01h,0.20,0.00
02h,0.14,0.00
03h,0.13,0.00
04h,0.12,0.00
05h,0.13,0.00
06h,0.11,0.00
07h,0.11,0.00
08h,0.17,0.12
09h,0.03,0.65
10h,0.05,1.25
11h,2.15,0.55
12h,1.50,1.09
13h,0.07,2.27
14h,0.02,2.33
15h,0.00,2.32
16h,0.65,1.62
17h,3.27,0.00
18h,0.88,0.78
19h,0.11,0.39
20h,0.16,0.04
```

**Comment by jgracio** [comment]
Quando vejo o gráfico do HA a energia exportada aparece-me o mesmo que aparece o CSV e no diagrama de 30 dias. No diagrama diário está compatível com a integração da potencia exportada

**Comment by nikito7** [comment]
O pico que tiveste no gráfico, não sei o motivo.

Mas o gráfico de 24h é baseado no "Energia Total Export". Precisão 2 décimas. 

O de 30dias é baseado nos LP**
Precisão 3 decimas.

A Precisão não iria causar o pico.

Se usas o HA podes ignorar o gráfico das 24h...

**Comment by nikito7** [comment]
Se o Easy HAN fizer reboot acontece coisas estranhas nesses gráficos internos...

**Comment by nikito7** [comment]
![Screenshot_20230803_210635_Chrome](https://github.com/nikito7/easyhan/assets/45373783/ad6e6d6c-acab-4b9d-94da-9a86a22708f4)

![Screenshot_20230803_210714_Chrome](https://github.com/nikito7/easyhan/assets/45373783/4d95865c-5f7e-4a1c-8a4f-e24fe88acc8b)

**Comment by jgracio** [comment]
Eu pretendo usar apenas o HA mas as curvas de exportação não estão corretas
![image](https://github.com/nikito7/easyhan/assets/25244815/4e80425f-a228-48b7-afca-429f1eabef06)

**Comment by nikito7** [comment]
"Calculation LP Export Inc,LP6_EXP"

Não há qualquer calculo nisto, valores reais.
Mas não são iguais à e-redes.

Os da e-redes são manipulados (*4).

De resto o importante é o que aparece no HA.

A parte dos LP precisa de um yaml adicional

**Comment by jgracio** [comment]
O meu yaml no HA é:
`
    - name: "Contador - Quarto Hora Exportação"
      unique_id: EB1_LP6_EXP
      state_topic: "tele/contador_pp/SENSOR"
      value_template: >-
          {% set x = value_json.EB1.LP6_EXP|float(0) %}
          {% if x >= 0 %}
            {{ x }}
          {% endif %}
      unit_of_measurement: "kWh"
      device_class: energy`

**Comment by nikito7** [comment]
Esse sensor só por si não faz nada.

Já agora tens a parte das contas?

![Screenshot_20230803_211542_Chrome](https://github.com/nikito7/easyhan/assets/45373783/7aea950c-c0ab-446d-9e35-a9eccf49119d)

**Comment by jgracio** [comment]
![image](https://github.com/nikito7/easyhan/assets/25244815/2aeb0ec8-fa27-4d5e-90ed-6f5ed7549a7a)

**Comment by nikito7** [comment]
https://gist.github.com/nikito7/034a28d1035cb236171e9cd78e18843a

**Comment by nikito7** [comment]
https://github.com/nikito7/easyhan/blob/dev/edpbox/eb1-script.js

**Comment by nikito7** [comment]
Por aqui aparentemente está tudo bem.

Tens de actualizar o script e yaml

![Screenshot_20230803_212130_Chrome](https://github.com/nikito7/easyhan/assets/45373783/a417521f-4353-430a-93fe-bcbc6ee3cd2e)

**Comment by jgracio** [comment]
O yaml que uso é identico e o script Tasmota que tenho instalado 
é o da semana passada

**Comment by nikito7** [comment]
Dizer o ver= que aparece no topo do tasmota ajuda qualquer coisa

**Comment by jgracio** [comment]
é a versão anterior 10283

**Comment by jgracio** [comment]
Vou ver se descubro o que se passa ou arranjar uma alternativa.  Obrigado pela ajuda mas pelos visto não é um problema da configuração

**Comment by nikito7** [comment]
Havia esse problema apenas no saldo.

https://github.com/nikito7/easyhan/commit/53c0146aa84706a6e9a7485901b4957d3c9f3f46

**Comment by jgracio** [comment]
No meu CSV não aparece a exportação no periodos das 13:00 (que ocorreu na realidade) -> este é só um exemplo porque esta atenuação ocorre sempre.

![image](https://github.com/nikito7/easyhan/assets/25244815/5fedea64-67f1-4967-a923-173228168578)

**Comment by nikito7** [comment]
Só que esses valores são reais....

Quanto muito pode ser o contador a causar isso....

**Comment by nikito7** [comment]
Se tiveres consumo residual é dificil ver.

Se tiveres poucos painéis. A casa pode absorver tudo.

Acho que o código não tem bug.

É uma questão de percepção dos dados.

Ou posso estar enganado 😅

**Comment by nikito7** [comment]
Também posso estar a ler o register errado

**Comment by nikito7** [comment]
Compara com o xlsx da e-redes (dividir por 4) tem de bater certo

**Comment by jgracio** [comment]
Se fosse um problema do contador não seria possível aparecerem dados reais nos gráficos diários?

**Comment by jgracio** [comment]
> Compara com o xlsx da e-redes (dividir por 4) tem de bater certo

Vou voltar a fazer isso

**Comment by nikito7** [comment]
Os gráficos diários usam as leituras.

Entre o lp3 e o lp6 existe as reativas.
Posso estar a ler a coisa errada

**Comment by nikito7** [comment]
EB1:

1,01441dx8x4xxUUuuUUuu@i7:1000,LP Import Inc,kWh,LP3_IMP,3
; lp4
; lp5
1,01441dx8x8x8xxUUuuUUuu@i7:1000,LP Export Inc,kWh,LP6_EXP,3

EB3:

1,01441dx8x4xxUUuuUUuu@i7:1000,LP Import Inc,kWh,LP3_IMP,3
;
1,01441dx8x8x8xxUUuuUUuu@i7:1000,LP Export Inc,kWh,LP6_EXP,3

#

**Comment by jgracio** [comment]
A e-redes apenas tem disponível 2 dias em Agosto
Os gráficos da energia importada coincidem

E estes são os da exportada

![image](https://github.com/nikito7/easyhan/assets/25244815/9d48eaf4-0363-4659-94d6-d235f981e099)

**Comment by jgracio** [comment]
> 1,01441dx8x4xxUUuuUUuu@i7:1000,LP Import Inc,kWh,LP3_IMP,3
> ; lp4
> ; lp5
> 1,01441dx8x8x8xxUUuuUUuu@i7:1000,LP Export Inc,kWh,LP6_EXP,3

Já tinha verificado essas linhas carater a carater. Estão iguais ao que tens aqui no github

**Comment by jgracio** [comment]
> Os gráficos diários usam as leituras.
> 
> Entre o lp3 e o lp6 existe as reativas. Posso estar a ler a coisa errada

Poderá ser uma possibilidade.... mas será um problema apenas no caso do meu contador?

**Comment by nikito7** [comment]
Começo a achar que é o contador.

Esses gráficos são gerados dos .csv

O 0d.csv pode ser errático 

Os LP-xxxx.csv deveriam ser precisos.
Excepto que pode faltar linhas ou duplicar, em raras excepções

**Comment by nikito7** [comment]
> > Os gráficos diários usam as leituras.
> > Entre o lp3 e o lp6 existe as reativas. Posso estar a ler a coisa errada
> 
> Poderá ser uma possibilidade.... mas será um problema apenas no caso do meu contador?

Pode não ter a ordem correcta.

É uma questão de ver em hex.

Sensor53 d1

A linha 0144

**Comment by jgracio** [comment]
22:36:17.795 > 01 44 06 01 83 ad 
22:36:17.898 : 01 44 1d 07 e7 08 03 04 16 1e 00 00 80 00 80 00 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by jgracio** [comment]
Agora tenho que fazer Sensor53 d0   ?


> 1d 07 e7 08 03 04 16 1e

Nesta altura a exportação está a zero

**Comment by nikito7** [comment]
> 22:36:17.795 > 01 44 06 01 83 ad
> 22:36:17.898 : 01 44 1d 07 e7 08 03 04 16 1e 00 00 80 00 80 00 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00

A linha não está completa



> Agora tenho que fazer Sensor53 d0 ?

Sim

**Comment by jgracio** [comment]
Há alguma forma de enviar o output para um ficheiro de texto?

**Comment by jgracio** [comment]
22:52:12.162 > 01 44 06 01 83 ad 
22:52:12.268 : 01 44 1d 07 e7 08 03 04 16 2d 00 00 80 00 80 00 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00 
22:52:12.310 : 12 36

**Comment by nikito7** [comment]
> Há alguma forma de enviar o output para um ficheiro de texto?

Só syslog ou http acho eu

**Comment by nikito7** [comment]
> 22:52:12.162 > 01 44 06 01 83 ad 22:52:12.268 : 01 44 1d 07 e7 08 03 04 16 2d 00 00 80 00 80 00 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00 22:52:12.310 : 12 36

01 44 1d
07 e7 08 03 04 16 2d 00 00 80 00 80 clock
00 amr status
00 00 00 02 lp3
00 00 00 00 lp4
00 00 00 00 lp5
00 00 00 00 lp6
12 36 crc

**Comment by jgracio** [comment]
lp3 importada e lp6 exportada?

**Comment by nikito7** [comment]
> lp3 importada e lp6 exportada?

Sim. A meio as reativas.

A 7 e 8 nao peço

**Comment by jgracio** [comment]
para mim já estou a entrar em áreas transcendentais 😃

**Comment by jgracio** [comment]
> > lp3 importada e lp6 exportada?
> 
> Sim. A meio as reativas.
> 
> A 7 e 8 nao peço

daí o endereço lido ser mais curto

**Comment by jgracio** [comment]
r01440601

**Comment by nikito7** [comment]
O tasmota não aguentava tudo. Nao sei se esse bug ainda existe.

01 44 08 01 ou simplesmente 01 44 00 01 salvo erro

Isso são endereços especiais.

**Comment by nikito7** [comment]
https://github.com/nikito7/edpbox-dev/blob/dev/DEF-C44-509.pdf

**Comment by jgracio** [comment]
Pois, transcendental para mim.
Amanhã vou ver se consigo estar à espreita quando estiver a exportar.

Obrigado pela ajuda

**Comment by jgracio** [comment]
Desculpa insistir com este assunto:

Sendo a estrutura da linha:
01 44 1d
07 e7 08 03 04 16 2d 00 00 80 00 80 clock
00 amr status
00 00 00 02 lp3
00 00 00 00 lp4
00 00 00 00 lp5
00 00 00 00 lp6
12 36 crc

O filtro de extracção do LP6 está correto? 
1,01441dx8x8x8xxUUuuUUuu@i7:1000,LP Export Inc,kWh,LP6_EXP,3

**Comment by nikito7** [comment]
> 07 e7 08 03 04 16 2d 00 00 80 00 80 clock 12 
> 00 amr status 1
> 00 00 00 02 lp3 4
> 00 00 00 00 lp4 4
> 00 00 00 00 lp5 4
> 00 00 00 00 lp6




> O filtro de extracção do LP6 está correto?
> 1,01441dx8x8x8xxUUuuUUuu@i7:1000,LP Export Inc,kWh,LP6_EXP,3

8+8+8+1

Acho que sim

**Comment by jgracio** [comment]
A energia exportada é o LP4. 
Alterei o script para 
1,01441dx8x8xxUUuuUUuu@i7:1000,LP Export Inc,kWh,LP6_EXP,3

E funciona às mil maravinhas.

Depreendo que os diagramas diários (hoje, ontem e anteontem) vão buscar os dados horários diretamente ao contador

**Comment by nikito7** [comment]
É porque mudaram as coisas

**Comment by nikito7** [comment]
01 44 1d 
07 e7 08 04 05 0d 0f 00 00 80 00 80
00
00 00 00 07 - 7 hW
00 00 00 00
00 00 00 00
00 00 02 2a - 554 Wh
e9 ea - crc

![Screenshot_20230804_132903_Chrome](https://github.com/nikito7/easyhan/assets/45373783/8fe35994-bb5a-4671-a81e-a03019fcbdbc)

E agora quem está certo? 🤣🤷‍♂️

**Comment by nikito7** [comment]
> Depreendo que os diagramas diários (hoje, ontem e anteontem) vão buscar os dados horários diretamente ao contador

Sim Energy Import kWh

**Comment by nikito7** [comment]
![Screenshot_20230804_135357_Chrome](https://github.com/nikito7/easyhan/assets/45373783/ef1fe165-1dcc-478c-9940-70ca8f89eb3b)

**Comment by jgracio** [comment]
12:15:53.893
 01 44 06 01 83 ad 
01 44 1d
 07 e7 08 04 05 0c 0f 00 00 80 00 80
 00
 00 00 00 00 -> 0Wh
 00 00 02 1f ->543Wh
 00 00 00 00
 00 00 00 0e 
93 b9

**Comment by nikito7** [comment]
Isso só tu podes confirmar.

Ir buscar os "registers" é um bocado complicado

**Comment by nikito7** [comment]
https://github.com/nikito7/edpbox-dev/blob/dev/tasmota/notes/profile-3-lite.js

**Comment by jgracio** [comment]
Confirmei com a integração da potencia e bater certo com os Wh. Certamente baterá certo com a informação da e-redes mas só amanhã consiguirei confirmar

**Comment by jgracio** [comment]
Confirmado.
Para o meu contador Kaifa MA109P a leitura correta para o LP de exportação é:
1,01441dx8x8xxUUuuUUuu@i7:1000,LP Export Inc,kWh,LP6_EXP,3

Obrigado @nikito7 pelo teu excelente trabalho com o Easyhan e pelo ajuda que me deste neste troubleshooting

**Comment by nikito7** [comment]
Isso é uma solução caso a caso.

Para manter o resto do script funcional.

É  o melhor sitio para alterar
