### ISSUE TITLE
[Sugestão] Alterar ficheiros de setup para permitir uso em casos que utilizam "reverse proxy" (e.g. nginx proxy_pass)

### ISSUE THREAD

**Issue by njascgil** [nikito7/easyhan#10]
Viva!
Tenho usado o Easy HAN com um endereço do tipo http://dominio.org/tasmota/... sem qualquer problema, até ao momento em que atualizei para a configuração que inclui os diagramas.
Neste caso, por causa das várias referências a "/ufs/", as páginas dos diagramas deixam de funcionar.
Consegui resolver deste lado a situação procurando as referências a "/ufs" e substituindo por "../ufs" todas elas, excepto as do script, onde usei "./ufs". Também alterei referências a "/" para "../" em dois ficheiros.
Tanto quanto me apercebi, esta alteração não parece ter nenhum efeito secundário.
Os ficheiros modificados (V2, EB1, 13-jul) estão aqui ([mod.zip](https://github.com/user-attachments/files/16285558/mod.zip)), caso se confirme a vantagem de implementar estas alterações.

**Comment by nikito7** [comment]
Feito. Acho eu

**Comment by njascgil** [comment]
Obrigado! Acabei de testar e parece-me tudo ok. A solução adotada é até um pouco mais simples que a da minha sugestão... ;-)

A única coisa que reparei não funcionar, mas também não funcionava com a alteração que sugeri, é a edição/criação de ficheiros no ufs (links com terminações do tipo /ufse?file=/0d.csv), pois dá um erro 404 ao premir "Save". Não é importante, pois deve ser pouco usado, e imagino que deverá implicar mudar algo no firmware...
