### ISSUE TITLE
HA 2023.8 - 2024.2.0 mqtt

### ISSUE THREAD

**Issue by nikito7** [nikito7/easyhan#3]
Ficheiros actualizados:

http://u.easyhan.pt/setup/EB1/

Ou no github.

Seguir os seguintes passos para evitar duplicados:

![1000013987](https://github.com/nikito7/easyhan/assets/45373783/a753d529-47cf-4163-8984-0a92468f689f)

Feito pela ordem correcta, deve ficar tudo na mesma...

**Comment by nikito7** [comment]
![Screenshot_20230805_133743_Home Assistant](https://github.com/nikito7/easyhan/assets/45373783/5b4bd4da-4079-4da4-949e-70b2430a2758)

**Comment by delorean-dev** [comment]
tambem é preciso mexer nos yamls?

**Comment by nikito7** [comment]
> tambem é preciso mexer nos yamls?

Sim, deixar de os usar.

**edit:**
Quer dizer, se usas apenas yaml não és afectado.

Apenas discovery/discovery*.txt
